# Generated by Django 3.1.1 on 2020-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200910_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='organisation',
        ),
        migrations.AddField(
            model_name='track',
            name='organisations',
            field=models.ManyToManyField(to='database.Organisation'),
        ),
    ]
