# Generated by Django 3.1.1 on 2020-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200910_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(through='database.TrackTag', to='database.Tag'),
        ),
    ]
