# Generated by Django 3.1.1 on 2020-09-10 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200910_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='organisations',
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, through='database.TrackTag', to='database.Tag'),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.organisation')),
                ('tracks', models.ManyToManyField(to='database.Track')),
            ],
        ),
    ]
