# Generated by Django 3.1.1 on 2020-09-10 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200910_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
