# Generated by Django 3.1.1 on 2020-09-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200911_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.organisation'),
        ),
    ]
