# Generated by Django 3.1.1 on 2020-09-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200911_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='tracks',
            field=models.ManyToManyField(blank=True, through='database.TrackTag', to='database.Track'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='database.Track'),
        ),
    ]
