# Generated by Django 3.1.1 on 2020-09-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200911_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, through='database.TrackTag', to='database.Tag'),
        ),
    ]
